### ISSUE TITLE
Hide content using scroll

### ISSUE THREAD

**Issue by unboxme** [hey24sheep/backdrop_modal_route#1]
Thank you for the awesome package! 🔥
It's really easy to use.

I got an idea for a feature: to hide content by scrolling like if you are using `showModalBottomSheet(...)` in Flutter or like iOS 13 style modal screens.

What do you think about this?

**Comment by hey24sheep** [comment]
Hi @unboxme, I am glad my package helped you. I thought of doing that but it is not user friendly and instead it will create a bug and will confuse end users. 

Issue arises when user have GestureDetector, ChildScroll or List View as their overlay content child. Which makes our parent drag fail. 

I have left that feature for user to implement as you have the power to do anything with the backdrop. If drag hide is needed user could add it as parent of OverlayContent and it will work for them.

**Comment by hey24sheep** [comment]
Closing in respect to latest readme update. This is added to FAQ in Readme.
