### ISSUE TITLE
auto height

### ISSUE THREAD

**Issue by pishguy** [hey24sheep/backdrop_modal_route#2]
thanks to share the library

how can we set auto height for children? in your sample in documents `height` is full screen for small children's height

**Comment by hey24sheep** [comment]
It will show whatever overlay content builder return. So if you have half height widgets it will adjust that way. This library is providing an easy way to create backdrops. It just displays whatever you create and return in overlay content builder. 

If you are talking about height of the modal itself. Then you can give top padding to make it smaller as per your need.
