### ISSUE TITLE
Setstate issue

### ISSUE THREAD

**Issue by CodeZee7** [hey24sheep/backdrop_modal_route#3]
I have a list of 'dhikrs', which are basically counters made by the user. When the user clicks on one, it brings up a backdrop modal route that displays the name, count, completion etc. of the counter. When the user taps on the Inkwell, the setstate is called which increments the "dhikr.completed" by 1. This is the counter value of the specific counter they chose at the beginning. However, the screen does not show the updated counter value. It only updates when the backdrop modal route is closed and then reopened.

I have a feeling this is because the value of the counter isn't just an int variable like '_counter' in the example. In my case it is an attribute from a class. (All counters are also stored in a DB)

Here is a snippet showing what i have described:
`return ListView(
                      children: snapshot.data.map<Widget>((dhikr) {
                        return Column(
                          children: [
                            InkWell(
                              onTap: () async {
                                await Navigator.push(
                                  context,
                                  BackdropModalRoute<void>(
                                    topPadding: 90,
                                    backdropShape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.vertical(
                                            top: Radius.circular(24))),
                                    overlayContentBuilder: (context) {
                                      return SafeArea(
                                        child: Container(
                                          height: MediaQuery.of(context)
                                              .size
                                              .height,
                                          decoration: BoxDecoration(
                                            color: Colors.white,
                                          ),
                                          alignment: Alignment.center,
                                          padding: const EdgeInsets.all(10),
                                          child: Column(
                                            children: <Widget>[
                                              Expanded(
                                                child: InkWell(
                                                  onTap: () {
                                                    setState(() {
                                                      dhikr.completed++;
                                                    });
                                                  },`

The text displaying the counter:
`                                                        Text(
                                                          '${dhikr.completed}',
                                                          style: TextStyle(
                                                              fontFamily:
                                                                  'avenir',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w900,
                                                              color:
                                                                  Colors.black,
                                                              fontSize: 50),
                                                        ),`

**Comment by hey24sheep** [comment]
Could you try completed +=1 instead of ++.. if that doesn't work could you try making an increment function in your logic class "dhikr" and call that function instead.
