### ISSUE TITLE
is there any way to use it with the go router?

### ISSUE THREAD

**Issue by IgordeOliveira** [hey24sheep/backdrop_modal_route#5]
I am using go router in my project and would like to treat this modal as a route, but it returns a non-widget type, and go router only accepts Material Page like widgets, is there any way to make this happen?

**Comment by hey24sheep** [comment]
Hi, I would recommend you to go through the readme once. This modal is route enabled. It can be stateful or stateless. So, I do think you can use it with go router.

**Comment by hey24sheep** [comment]
If you use this with "GoRouter" feel free to add your sample here for anyone else. I have personally not used "GoRouter", so I can't help much.

I am closing this issue, if something is missing in the library then a detailed description would be helpful. Feel free to re-open if needed, thank you.
